"""Alter Col summary on Users

Revision ID: 161adc58373e
Revises: 69f61bafb5d1
Create Date: 2022-08-04 22:31:15.669580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161adc58373e'
down_revision = '69f61bafb5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'summary',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'summary',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
