"""Connnect SocialNetworks and Users

Revision ID: 69f61bafb5d1
Revises: 68a506e3ffb6
Create Date: 2022-08-04 21:14:51.513106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f61bafb5d1'
down_revision = '68a506e3ffb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_social_networks',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('social_network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['social_network_id'], ['social_network.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_social_networks')
    # ### end Alembic commands ###
